version: '3'
services:
  web:
    build: .
    command: pm2-runtime start --watch ecosystem.config.js
    ports:
      - "3000:3000"
      - "3100:3100"
    volumes:
      - .:/var/www
    links:
        - mongo
    depends_on:
        - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
